<!--Managed by batou: do not edit this file directly. It will be overwritten!-->

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/frameset.dtd">
<html>
  <head>
    <script type="text/javascript">
      function doLogin() {
          contentDocument = parent.frames.youtrack_content.document;
          if (contentDocument == undefined) {
              return setTimeout('doLogin()', 1000); }
          userInput = contentDocument.getElementById('username'); 
          if (userInput == undefined) {
              return setTimeout('doLogin()', 1000); }
          userInput.value = '<?php echo $_GET['userName']; ?>';
          contentDocument.getElementById('password').value = '<?php echo $_GET['password']; ?>';
          contentDocument.getElementsByTagName('button')[0].click();
      }
    </script>
  </head>
  <body onload="setTimeout('doLogin()', 1000)">
    logging in...
  </body>
</html>
