<!--Managed by batou: do not edit this file directly. It will be overwritten!-->

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/frameset.dtd">
<html>
  <frameset rows="0, *" border="0" frameborder="0">
<?php echo '    <frame src="hiddenFrame.php?userName='.$_POST['userName'].'&password='.$_POST['password'].'" name="youtrack_hidden" marginheight="0" scrolling="no"/>'; ?>
    <frame src="/loginForm" name="youtrack_content" marginheight="0" scrolling="auto"/>
  </frameset>

  <body>
    <b><font style="color:#ff0000">Error:</font></b><br>
    need browser frame support to work.
  </body>
</html>
